services:
  spring-sec-postgres:
    container_name: spring-sec-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgres-spring-sec
    restart: always
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]

volumes:
  postgres_data:
